export const COMMON = {
  RESET_FIELD: 'RESET_FIELD',
  SHOW_LOADER: 'SHOW_LOADER',
  FUN_FACT: 'FUN_FACT',
};

// export const SESSION = {
// 	GET_USER_DETAILS: "GET_USER_DETAILS",
// 	SEND_LOGIN_CREDENTIALS: "SEND_LOGIN_CREDENTIALS",
// 	UPDATE_LOGIN_CREDENTIALS: "UPDATE_LOGIN_CREDENTIALS",
// 	SEND_FORGOT_PASSWORD_CREDENTIALS: "SEND_FORGOT_PASSWORD_CREDENTIALS",
// 	SEND_RESET_PASSWORD_CREDENTIALS: "SEND_RESET_PASSWORD_CREDENTIALS",
// 	CHANGE_PASSWORD: "CHANGE_PASSWORD",
// };

// export const SCHOOL = {
// 	GET_SCHOOL_LIST: "GET_SCHOOL_LIST",
// 	GET_GRADE_LIST: "GET_GRADE_LIST",
// 	SET_FILTER: "SET_SCHOOL_FILTER",
// 	CREATE_SCHOOL: "CREATE_SCHOOL",
// 	UPDATE_SCHOOL: "UPDATE_SCHOOL",
// 	DELETE_SCHOOL: "UPDATE_SCHOOL",
// 	GET_SECTION_LIST: "GET_SECTION_LIST",
// };
// export const PEOPLE = {
// 	GET_PEOPLE_LIST: "GET_PEOPLE_LIST",
// 	SET_FILTER: "SET_PEOPLE_FILTER",
// 	CREATE_PEOPLE: "CREATE_PEOPLE",
// 	UPDATE_PEOPLE: "UPDATE_PEOPLE",
// 	DELETE_PEOPLE: "UPDATE_PEOPLE",
// };
// export const PHOTO = {
// 	GET_PHOTO_LIST: "GET_PHOTO_LIST",
// 	SET_FILTER: "SET_PHOTO_FILTER",
// 	SELECT_PHOTO: "SELECT_PHOTO",
// };

// export const LAYOUT = {
// 	GET_LAYOUT_LIST: "GET_LAYOUT_LIST",
// 	CREATE_LAYOUT: "CREATE_LAYOUT",
// 	DELETE_LAYOUT: "DELETE_LAYOUT",
// };

export const LAYOUT = {
  CART_ITEM: 'CART_ITEM',
  CART_REMOVE: 'CART_REMOVE',
  CART_UPDATE: 'CART_UPDATE',
};

export const LOGIN = {
  LOGIN_DATA: 'LOGIN_DATA',
};
export const STATUSBAR = {
  STATUSBAR_HIDE: 'HIDE_STATUSBAR',
};

export const BUY = {
  BUY_ITEM: 'BUY_ITEM',
  BUY_REMOVE: 'BUY_REMOVE',
};
